markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Forrest Mao
url: http://forrest-mao.github.io
description: Things I wish I someone had told me about software and community 
weibo: forrestmao
github_username: forrest-mao
gravatar_url: http://www.gravatar.com/avatar/badc5772d0c4983791b2d812f4da6487.png 
email: mmaaoolliiffuu@gmail.com
